<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NmosController.Application</RootNamespace>
    <AssemblyName>NmosController.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NmosController.Domain\NmosController.Domain.csproj" />
    <ProjectReference Include="..\NmosController.Contracts\NmosController.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
